# Generated by Django 5.1.2 on 2024-12-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_address_street_address_street_add_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoraddress',
            old_name='street',
            new_name='street_add_1',
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='street_add_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='address_type',
            field=models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Billing and Shipping', 'Billing and Shipping')], max_length=30),
        ),
    ]
