# Generated by Django 5.1.2 on 2024-12-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_vendor_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='business_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(max_length=120),
        ),
    ]
