# Generated by Django 5.1.2 on 2024-12-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bcc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bcc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
