# Generated by Django 5.1.2 on 2024-12-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
