# Generated by Django 5.1.2 on 2025-02-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_vendor_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
