# Generated by Django 5.1.2 on 2024-12-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_newuser_last_login_city_newuser_last_login_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('last_login_city', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login_country', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.newuser')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action', 'timestamp'], name='authenticat_user_id_33a635_idx'), models.Index(fields=['model_name', 'record_id'], name='authenticat_model_n_d149e6_idx')],
            },
        ),
    ]
