# Generated by Django 5.1.2 on 2024-10-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('inventory', '0002_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_created', to='authentication.newuser'),
        ),
    ]
