# Generated by Django 5.1.2 on 2024-11-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_as_on_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
