# Generated by Django 5.1.2 on 2024-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_invoice_date_remove_invoice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attachments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_taxed',
            field=models.BooleanField(default=False),
        ),
    ]
