# Generated by Django 5.1.2 on 2024-11-28 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_newuser_last_login_city_newuser_last_login_country'),
        ('inventory', '0014_invoice_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='action',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='source',
        ),
        migrations.AddField(
            model_name='bill',
            name='attachments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_created_by', to='authentication.newuser'),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='mailing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
