# Generated by Django 5.1.2 on 2024-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_bill_action_remove_bill_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='bill_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
