# Generated by Django 5.1.2 on 2024-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_rename_created_at_bill_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
