# Generated by Django 5.1.2 on 2024-11-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_bill_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_no',
        ),
    ]
