# Generated by Django 5.1.2 on 2024-12-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_bill_mailing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sell_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='productaccountmapping',
            name='income_account',
        ),
    ]
