# Generated by Django 5.1.2 on 2024-12-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_account_type'),
        ('inventory', '0024_alter_product_barcode_alter_product_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTransactionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTransactionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
            ],
        ),
    ]
