# Generated by Django 5.1.2 on 2025-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_billtransactionmapping_bill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
