# Generated by Django 5.1.2 on 2025-02-24 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_last_login_city_auditlog_activity_city_and_more'),
        ('inventory', '0028_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_lost', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit at the time of loss.', max_digits=10)),
                ('total_loss', models.DecimalField(decimal_places=2, editable=False, help_text='Calculated as quantity_lost * unit_cost.', max_digits=10)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('other', 'Other')], default='damaged', max_length=50)),
                ('loss_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Additional details about the loss.', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_products_created', to='authentication.newuser')),
                ('invoice', models.ForeignKey(blank=True, help_text='Optional: Link to an invoice if the loss is related to a specific transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_products', to='inventory.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_products', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_products_updated', to='authentication.newuser')),
            ],
        ),
    ]
