# Generated by Django 5.1.2 on 2025-02-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_lostproduct_loss_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_code',
            field=models.IntegerField(default=0),
        ),
    ]
