# Generated by Django 5.1.2 on 2025-02-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_invoice_invoice_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_code',
        ),
    ]
