# Generated by Django 5.1.2 on 2025-02-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_lostproduct_transaction_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostproduct',
            old_name='transaction_map',
            new_name='transaction',
        ),
    ]
