# Generated by Django 5.1.2 on 2025-03-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ownerpaymentdetails_money_flag'),
        ('inventory', '0036_alter_bill_bill_date_alter_bill_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtransactionmapping',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_transactions', to='accounts.transaction'),
        ),
        migrations.AlterField(
            model_name='invoicetransactionmapping',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_transactions', to='accounts.transaction'),
        ),
    ]
