# Generated by Django 5.1.2 on 2025-03-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_billtransactionmapping_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtransactionmapping',
            name='is_payment_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicetransactionmapping',
            name='is_payment_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
