# Generated by Django 5.1.2 on 2025-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
