# Generated by Django 5.1.2 on 2025-02-28 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
