# Generated by Django 5.1.2 on 2024-12-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_receivabletracking_prepayment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivabletracking',
            old_name='prepayment_amount',
            new_name='advance_payment',
        ),
        migrations.AddField(
            model_name='payabletracking',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
