# Generated by Django 5.1.2 on 2024-12-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_prepayment_amount_receivabletracking_advance_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentdetails',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpaymentdetails',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
