# Generated by Django 5.1.2 on 2024-12-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customerpaymentdetails_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('accounts_receivable', 'Accounts Receivable'), ('inventory', 'Inventory'), ('fixed_assets', 'Fixed Assets'), ('other_current_assets', 'Other Current Assets'), ('accounts_payable', 'Accounts Payable'), ('Tax_payable', 'Tax Payable'), ('credit_card', 'Credit Card'), ('current_liabilities', 'Current Liabilities'), ('long_term_liabilities', 'Long Term Liabilities'), ('owner_equity', 'Owner Equity'), ('retained_earnings', 'Retained Earnings'), ('sales_income', 'Sales Income'), ('service_income', 'Service Income'), ('other_income', 'Other Income'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('operating_expenses', 'Operating Expenses'), ('payroll_expenses', 'Payroll Expenses'), ('marketing_expenses', 'Marketing Expenses'), ('administrative_expenses', 'Administrative Expenses'), ('other_expenses', 'Other Expenses')], max_length=100),
        ),
    ]
