# Generated by Django 5.1.2 on 2025-01-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_ownerpaymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpaymentdetails',
            name='transaction_type',
            field=models.CharField(choices=[('money_added', 'Money Added'), ('money_removed', 'Money Removed')], default='money_added', max_length=20),
        ),
    ]
