# Generated by Django 5.1.2 on 2025-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ownerpaymentdetails_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpaymentdetails',
            name='money_flag',
            field=models.IntegerField(default=1),
        ),
    ]
