# Generated by Django 5.1.2 on 2025-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ownerpaymentdetails_money_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionline',
            name='bill_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='invoice_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
